# File name: drawingspace.kv
<DrawingSpace@RelativeLayout>: # Drawing space is a subclass of relative layout
	Label:
	# Kivy markup styles the text of the label class in a similar manner to xml based languages, i.e. HTML.
		markup: True
		text: '[size=32px][color=#3e6643]The[/color] [sub]Comic[/sub] [i][b]Creator[/b][/i][/size]'
		# The complete list and description is here: https://kivy.org/doc/stable/api-kivy.uix.label.html